# Generated by Django 2.2.5 on 2019-12-16 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='TeamRivalryID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamRivalry'),
        ),
    ]
