# Generated by Django 2.2.5 on 2019-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_Deflections',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_INT',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_INTTD',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_INTYards',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_QBHits',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_Sacks',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_SoloTackles',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_TD',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_Tackles',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='DEF_TacklesForLoss',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='FUM_Fumbles',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='FUM_Lost',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='FUM_Recovered',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGA',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGM',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_XPA',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_XPM',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KR_Returns',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KR_TD',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KR_Yards',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PAS_Attempts',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PAS_Completions',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PAS_INT',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PAS_SackYards',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PAS_Sacks',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PAS_TD',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PAS_Yards',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PNT_Punts',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PNT_Touchbacks',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PNT_Within20',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PNT_Yards',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PR_Returns',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='PR_TD',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='REC_Receptions',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='REC_TD',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='REC_Targets',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='REC_Yards',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='RUS_Carries',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='RUS_TD',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='RUS_Yards',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
