# Generated by Django 2.2.5 on 2019-12-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0002_auto_20191205_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='AwayTeamID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='AwayTeamRecord',
        ),
        migrations.RemoveField(
            model_name='game',
            name='AwayTeamScore',
        ),
        migrations.RemoveField(
            model_name='game',
            name='AwayTeamSeasonDateRankID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='AwayTeamSeed',
        ),
        migrations.RemoveField(
            model_name='game',
            name='HomeTeamID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='HomeTeamRecord',
        ),
        migrations.RemoveField(
            model_name='game',
            name='HomeTeamScore',
        ),
        migrations.RemoveField(
            model_name='game',
            name='HomeTeamSeasonDateRankID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='HomeTeamSeed',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TournamentGameNumber',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TournamentRegionID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TournamentRoundID',
        ),
        migrations.RemoveField(
            model_name='playergamestat',
            name='GameID',
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='TeamGameID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Game'),
        ),
        migrations.CreateModel(
            name='TeamGame',
            fields=[
                ('TeamGameID', models.AutoField(primary_key=True, serialize=False)),
                ('TeamScore', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('GameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Game')),
                ('TeamSeasonDateRankID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamSeasonDateRank')),
                ('TeamSeasonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamSeason')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
