# Generated by Django 2.2.5 on 2019-12-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0003_auto_20191205_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='IsHomeTeam',
            field=models.BooleanField(default=False),
        ),
    ]
