# Generated by Django 2.2.5 on 2019-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0004_calendar_weekid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgame',
            name='Points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
