# Generated by Django 2.2.5 on 2019-12-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0004_teamgame_ishometeam'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamseason',
            name='GamesPlayed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
