# Generated by Django 2.2.5 on 2019-12-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0005_auto_20191216_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueseason',
            name='ConferenceChampionshipsCreated',
            field=models.BooleanField(default=False),
        ),
    ]
