# Generated by Django 2.2.5 on 2019-12-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0005_playerteamseason_gamesplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='TeamRecord',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
