# Generated by Django 2.2.5 on 2019-12-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0006_leagueseason_conferencechampionshipscreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('BowlID', models.AutoField(primary_key=True, serialize=False)),
                ('BowlName', models.CharField(max_length=50)),
                ('Team1Rank', models.PositiveSmallIntegerField(default=0)),
                ('Team2Rank', models.PositiveSmallIntegerField(default=0)),
                ('IsNationalChampionship', models.BooleanField(default=False)),
                ('BowlPrestige', models.PositiveSmallIntegerField(default=0)),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
