# Generated by Django 2.2.5 on 2019-12-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0007_auto_20191206_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Acceleration_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Agility_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Awareness_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='BallCarrierVision_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='BlockShedding_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Carrying_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='CatchInTraffic_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Catching_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='DeepThrowAccuracy_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Elusiveness_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='FinesseMoves_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='ImpactBlock_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Injury_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='JukeMove_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Jumping_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='KickAccuracy_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='KickPower_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='KickReturn_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='ManCoverage_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='MediumThrowAccuracy_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='PassBlock_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='PlayAction_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='PlayRecognition_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='PowerMoves_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Press_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Pursuit_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Release_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='RouteRunning_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='RunBlock_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='RunningThrowAccuracy_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='ShortThrowAccuracy_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='SpectacularCatch_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Speed_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='SpinMove_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Stamina_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='StiffArm_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Strength_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Tackle_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='ThrowPower_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Toughness_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='Trucking_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='ZoneCoverage_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
