# Generated by Django 2.2.5 on 2019-12-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0008_game_bowlid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='IsConferenceChampionship',
            field=models.BooleanField(default=False),
        ),
    ]
