# Generated by Django 2.2.5 on 2019-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0008_auto_20191206_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerteamseason',
            name='Possessions',
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='GamesStarted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
