# Generated by Django 2.2.5 on 2019-12-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0009_auto_20191206_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamestat',
            name='Started',
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='GamesStarted',
            field=models.SmallIntegerField(default=0),
        ),
    ]
