# Generated by Django 2.2.5 on 2019-12-18 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0009_game_isconferencechampionship'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueseason',
            name='BowlCreationDateID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BowlCreationDateID', to='HeadFootballCoach.Calendar'),
        ),
    ]
