# Generated by Django 2.2.5 on 2019-12-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0010_auto_20191206_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamestat',
            name='TeamGameID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamGame'),
        ),
    ]
