# Generated by Django 2.2.5 on 2019-12-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0010_leagueseason_bowlcreationdateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerteamseasonaward',
            name='IsMonthAward',
        ),
        migrations.AlterField(
            model_name='team',
            name='TeamJerseyStyle',
            field=models.CharField(default='football', max_length=20),
        ),
    ]
