# Generated by Django 2.2.5 on 2019-12-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0011_auto_20191206_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRivalry',
            fields=[
                ('TeamRivalryID', models.AutoField(primary_key=True, serialize=False)),
                ('RivalryName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Team1TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='HeadFootballCoach.Team')),
                ('Team2TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='HeadFootballCoach.Team')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
