# Generated by Django 2.2.5 on 2019-12-19 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0011_auto_20191219_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamseasonaward',
            name='WeekID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Week'),
        ),
    ]
