# Generated by Django 2.2.5 on 2019-12-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0012_teamrivalry'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_PlayerArchetypeRatingModifier',
            fields=[
                ('System_PlayerArchetypeRatingModifierID', models.AutoField(primary_key=True, serialize=False)),
                ('Position', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Archetype', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Strength_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Agility_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Speed_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Acceleration_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Stamina_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Awareness_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Jumping_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Injury_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Toughness_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ThrowPower_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ShortThrowAccuracy_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('MediumThrowAccuracy_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('DeepThrowAccuracy_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('RunningThrowAccuracy_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PlayAction_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Trucking_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Elusiveness_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('BallCarrierVision_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('StiffArm_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('SpinMove_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('JukeMove_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Carrying_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Catching_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('CatchInTraffic_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('RouteRunning_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('SpectacularCatch_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Release_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Tackle_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PowerMoves_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('FinesseMoves_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('BlockShedding_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Pursuit_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PlayRecognition_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ManCoverage_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ZoneCoverage_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Press_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PassBlock_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('RunBlock_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ImpactBlock_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('KickPower_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('KickAccuracy_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('KickReturn_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
