# Generated by Django 2.2.5 on 2019-12-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0013_conference_conferencelogourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='FUM_Forced',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='FUM_Forced',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='FUM_Forced',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='FUM_Forced',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='JerseyNumber',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='Position',
            field=models.CharField(default='QB', max_length=3),
        ),
    ]
