# Generated by Django 2.2.5 on 2019-12-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0013_system_playerarchetyperatingmodifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_playerarchetyperatingmodifier',
            name='BreakTackle_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
