# Generated by Django 2.2.5 on 2019-12-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0014_system_playerarchetyperatingmodifier_breaktackle_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_playerarchetyperatingmodifier',
            old_name='RouteRunning_Rating',
            new_name='DeepRouteRunning_Rating',
        ),
        migrations.RenameField(
            model_name='system_playerarchetyperatingmodifier',
            old_name='RunningThrowAccuracy_Rating',
            new_name='ThrowOnRun_Rating',
        ),
        migrations.AddField(
            model_name='system_playerarchetyperatingmodifier',
            name='HitPower_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='system_playerarchetyperatingmodifier',
            name='MediumRouteRunning_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='system_playerarchetyperatingmodifier',
            name='ShortRouteRunning_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
