# Generated by Django 2.2.5 on 2019-12-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0014_auto_20191220_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='WorldID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
