# Generated by Django 2.2.5 on 2019-12-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0015_auto_20191207_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_playerarchetyperatingmodifier',
            name='ThrowUnderPressure_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
