# Generated by Django 2.2.5 on 2019-12-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0015_auto_20191222_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='DateID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='IsCurrent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='CityID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='ConferenceID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='WasPlayed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='GameEventID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='league',
            name='LeagueID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leagueseason',
            name='IsCurrent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='leagueseason',
            name='LeagueSeasonID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='IsRecruit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='PlayerID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='Recruiting_NationalRank',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='playergamestat',
            name='PlayerGameStatID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playerseasonskill',
            name='PlayerSeasonSkillID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playerteamseason',
            name='GamesPlayed',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerteamseason',
            name='PlayerTeamSeasonID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playerteamseasonaward',
            name='PlayerTeamSeasonAwardID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recruitteamseason',
            name='RecruitTeamSeasonID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='TeamID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamgame',
            name='IsHomeTeam',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='teamgame',
            name='TeamGameID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamrivalry',
            name='TeamRivalryID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='TeamSeasonID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamseasondaterank',
            name='IsCurrent',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='teamseasondaterank',
            name='TeamSeasonDateRankID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='week',
            name='WeekID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='week',
            name='WeekNumber',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
