# Generated by Django 2.2.5 on 2019-12-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0016_system_playerarchetyperatingmodifier_throwunderpressure_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='RouteRunning_Rating',
        ),
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='RunningThrowAccuracy_Rating',
        ),
        migrations.AddField(
            model_name='playerseasonskill',
            name='BreakTackle_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonskill',
            name='DeepRouteRunning_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonskill',
            name='HitPower_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonskill',
            name='MediumRouteRunning_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonskill',
            name='ShortRouteRunning_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonskill',
            name='ThrowOnRun_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonskill',
            name='ThrowUnderPressure_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
