# Generated by Django 2.2.5 on 2019-12-22 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0016_auto_20191222_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='CurrentDay',
        ),
        migrations.RemoveField(
            model_name='game',
            name='GameDateID',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='BowlCreationDateID',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='CoachCarouselDateID',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='CoachCarouselExecuted',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='IncomingPlayerArrivalDayDateID',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='IncomingPlayerArrivalDayExecuted',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='NextSeasonCutoverDayDateID',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='NextSeasonCutoverDayExecuted',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='PlayerDepartureDayDateID',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='PlayerDepartureDayExecuted',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='RankingsLastCalculated',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='RecruitingSigningDayDateID',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='RecruitingSigningDayExecuted',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='RegularSeasonEndDateID',
        ),
        migrations.RemoveField(
            model_name='leagueseason',
            name='RegularSeasonStartDateID',
        ),
        migrations.AddField(
            model_name='driver',
            name='CurrentWeek',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Week'),
        ),
        migrations.AddField(
            model_name='game',
            name='WeekID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Week'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='DateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Week'),
        ),
        migrations.CreateModel(
            name='TeamSeasonWeekRank',
            fields=[
                ('TeamSeasonWeekRankID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('IsCurrent', models.BooleanField(db_index=True, default=True)),
                ('NationalRank', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('NationalRankDelta', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('PollPoints', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('DateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Week')),
                ('TeamSeasonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamSeason')),
                ('WorldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
