# Generated by Django 2.2.5 on 2019-12-22 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0017_auto_20191222_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('PhaseID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
        migrations.AddField(
            model_name='week',
            name='PhaseID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Phase'),
        ),
    ]
