# Generated by Django 2.2.5 on 2019-12-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0017_auto_20191207_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamgame',
            old_name='TeamScore',
            new_name='Points',
        ),
        migrations.AddField(
            model_name='teamgame',
            name='TimeOfPossession',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
    ]
