# Generated by Django 2.2.5 on 2019-12-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0018_auto_20191222_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='PhaseName',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='LastWeekInPhase',
            field=models.BooleanField(default=False),
        ),
    ]
