# Generated by Django 2.2.5 on 2019-12-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0019_auto_20191222_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='WeekName',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
