# Generated by Django 2.2.5 on 2019-12-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0020_week_weekname'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='IsCurrent',
            field=models.BooleanField(default=False),
        ),
    ]
