# Generated by Django 2.2.5 on 2019-12-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0021_week_iscurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='BroadcastSelected',
            field=models.BooleanField(default=False),
        ),
    ]
