# Generated by Django 2.2.5 on 2019-12-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0021_auto_20191207_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='GameScore',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='GameScore',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
    ]
