# Generated by Django 2.2.5 on 2019-12-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0022_auto_20191207_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameevent',
            old_name='AwayTeamScore',
            new_name='AwayPoints',
        ),
        migrations.RenameField(
            model_name='gameevent',
            old_name='HomeTeamScore',
            new_name='HomePoints',
        ),
    ]
