# Generated by Django 2.2.5 on 2019-12-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0023_auto_20191208_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='IsScoringPlay',
            field=models.BooleanField(default=True),
        ),
    ]
