# Generated by Django 2.2.5 on 2019-12-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0024_auto_20191222_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamseasonaward',
            name='AwardPosition',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseasonaward',
            name='AwardPositionGrouping',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseasonaward',
            name='IsPreseasonAward',
            field=models.BooleanField(default=False),
        ),
    ]
