# Generated by Django 2.2.5 on 2019-12-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0025_auto_20191222_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='LeagueSeasonID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.LeagueSeason'),
        ),
    ]
