# Generated by Django 2.2.5 on 2019-12-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0026_auto_20191208_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='Turnovers',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='Turnovers',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
