# Generated by Django 2.2.5 on 2019-12-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0026_phase_leagueseasonid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('PositionID', models.AutoField(primary_key=True, serialize=False)),
                ('PositionAbbreviation', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('PositionName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('PositionCountPerAwardTeam', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PositionMinimumCountPerTeam', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
