# Generated by Django 2.2.5 on 2019-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0027_auto_20191208_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='FirstDowns',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='FirstDowns',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
