# Generated by Django 2.2.5 on 2019-12-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0027_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Position',
        ),
        migrations.AddField(
            model_name='player',
            name='PositionID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Position'),
        ),
        migrations.AddField(
            model_name='position',
            name='PositionSortOrder',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
