# Generated by Django 2.2.5 on 2019-12-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0028_auto_20191222_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerteamseasonaward',
            name='AwardPosition',
        ),
        migrations.AddField(
            model_name='playerteamseasonaward',
            name='PositionID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Position'),
        ),
        migrations.AddField(
            model_name='position',
            name='PositionGrouping',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
