# Generated by Django 2.2.5 on 2019-12-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0028_auto_20191208_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgame',
            name='TimeOfPossession',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='TimeOfPossession',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
