# Generated by Django 2.2.5 on 2019-12-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0029_auto_20191222_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerteamseasonaward',
            name='AwardPositionGrouping',
        ),
        migrations.AddField(
            model_name='playerteamseasonaward',
            name='IsIndividualAward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerteamseasonaward',
            name='IsPositionAward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerteamseasonaward',
            name='IsPositionGroupAward',
            field=models.BooleanField(default=False),
        ),
    ]
