# Generated by Django 2.2.5 on 2019-12-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0029_auto_20191208_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='OnsideKickTendency',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='coach',
            name='PlaycallPassTendency',
            field=models.PositiveSmallIntegerField(default=55),
        ),
    ]
