# Generated by Django 2.2.5 on 2019-12-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0030_auto_20191222_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='HeightAverage',
            field=models.DecimalField(decimal_places=2, default=72, max_digits=6),
        ),
        migrations.AddField(
            model_name='position',
            name='HeightStd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='position',
            name='Occurance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='RandomStart',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='RandomStop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='WeightAverage',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6),
        ),
        migrations.AddField(
            model_name='position',
            name='WeightStd',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
