# Generated by Django 2.2.5 on 2019-12-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0030_auto_20191209_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='FourthDownAttempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='FourthDownConversion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='ThirdDownAttempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='ThirdDownConversion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='FourthDownAttempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='FourthDownConversion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='ThirdDownAttempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='ThirdDownConversion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
