# Generated by Django 2.2.5 on 2019-12-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0031_auto_20191222_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionGroup',
            fields=[
                ('PositionGroupID', models.AutoField(primary_key=True, serialize=False)),
                ('PositionGroupName', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
    ]
