# Generated by Django 2.2.5 on 2019-12-13 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0031_auto_20191212_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='NextGameID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Game'),
        ),
    ]
