# Generated by Django 2.2.5 on 2019-12-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0032_positiongroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='PositionGrouping',
        ),
        migrations.AddField(
            model_name='position',
            name='PositionGroupID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.PositionGroup'),
        ),
    ]
