# Generated by Django 2.2.5 on 2019-12-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0033_auto_20191222_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamseasonaward',
            name='PositionGroupID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.PositionGroup'),
        ),
    ]
