# Generated by Django 2.2.5 on 2019-12-13 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0033_auto_20191213_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playoff',
            fields=[
                ('PlayoffID', models.AutoField(primary_key=True, serialize=False)),
                ('PlayoffStarted', models.BooleanField(default=False)),
                ('PlayoffCompleted', models.BooleanField(default=False)),
                ('IsPostseason', models.BooleanField(default=False)),
                ('TeamsInPlayoff', models.PositiveSmallIntegerField(default=0)),
                ('RoundsInPlayoff', models.PositiveSmallIntegerField(default=0)),
                ('ChampionTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Team')),
                ('LeagueSeasonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.LeagueSeason')),
                ('MostOutstandingPlayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Player')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffRound',
            fields=[
                ('PlayoffRoundID', models.AutoField(primary_key=True, serialize=False)),
                ('RoundStarted', models.BooleanField(default=False)),
                ('RoundCompleted', models.BooleanField(default=False)),
                ('PlayoffRoundNumber', models.PositiveSmallIntegerField(default=1)),
                ('MinGameNumber', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('MaxGameNumber', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('NumberOfGames', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('NumberOfTeams', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('WinValue', models.PositiveSmallIntegerField(default=1)),
                ('IsChampionshipRound', models.BooleanField(default=False)),
                ('IsFinalFour', models.BooleanField(default=False)),
                ('PlayoffID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Playoff')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
        migrations.CreateModel(
            name='System_PlayoffGame',
            fields=[
                ('PlayoffGameID', models.AutoField(primary_key=True, serialize=False)),
                ('GameNumber', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('PlayoffGameNumberInRound', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('NextPlayoffGameNumberInRound', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('NextPlayoffGameID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.System_PlayoffGame')),
            ],
        ),
        migrations.RenameModel(
            old_name='TournamentRegion',
            new_name='PlayoffRegion',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='ChampionTeam',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='LeagueSeasonID',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='MostOutstandingPlayer',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='WorldID',
        ),
        migrations.RemoveField(
            model_name='tournamentround',
            name='TournamentID',
        ),
        migrations.RemoveField(
            model_name='tournamentround',
            name='WorldID',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='NumberOfTournamentTeams',
            new_name='NumberOfPlayoffTeams',
        ),
        migrations.RenameField(
            model_name='playerteamseasonaward',
            old_name='IsTournamentAward',
            new_name='IsPlayoffAward',
        ),
        migrations.RenameField(
            model_name='playoffregion',
            old_name='TournamentRegionID',
            new_name='PlayoffRegionID',
        ),
        migrations.RenameField(
            model_name='playoffregion',
            old_name='TournamentRegionName',
            new_name='PlayoffRegionName',
        ),
        migrations.RenameField(
            model_name='system_playoffround',
            old_name='TournamentRoundID',
            new_name='PlayoffRoundID',
        ),
        migrations.RenameField(
            model_name='system_playoffround',
            old_name='TournamentRoundNumber',
            new_name='PlayoffRoundNumber',
        ),
        migrations.RenameField(
            model_name='teamseason',
            old_name='TournamentRank',
            new_name='PlayoffRank',
        ),
        migrations.RenameField(
            model_name='teamseason',
            old_name='TournamentRegionID',
            new_name='PlayoffRegionID',
        ),
        migrations.RenameField(
            model_name='teamseason',
            old_name='TournamentSeed',
            new_name='PlayoffSeed',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TournamentID',
        ),
        migrations.AlterField(
            model_name='league',
            name='LeagueType',
            field=models.CharField(choices=[('1', 'Pro'), ('2', 'International'), ('3', 'College'), ('4', 'High School'), ('5', 'International Playoff'), ('6', 'Amateur Playoff')], default='1', max_length=19),
        ),
        migrations.RenameModel(
            old_name='System_TournamentRound',
            new_name='System_PlayoffRound',
        ),
        migrations.DeleteModel(
            name='System_TournamentGame',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='TournamentRound',
        ),
        migrations.AddField(
            model_name='system_playoffgame',
            name='NextPlayoffRoundID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NextPlayoffRoundID', to='HeadFootballCoach.System_PlayoffRound'),
        ),
        migrations.AddField(
            model_name='system_playoffgame',
            name='ThisPlayoffRoundID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ThisPlayoffRoundID', to='HeadFootballCoach.System_PlayoffRound'),
        ),
        migrations.AddField(
            model_name='game',
            name='PlayoffID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Playoff'),
        ),
    ]
