# Generated by Django 2.2.5 on 2019-12-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0034_playerteamseasonaward_positiongroupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='FUM_ReturnTD',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='FUM_ReturnYards',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='FUM_ReturnTD',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='FUM_ReturnYards',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='FUM_ReturnTD',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='FUM_ReturnYards',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
