# Generated by Django 2.2.5 on 2019-12-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0035_auto_20191224_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='FUM_ReturnTD',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='FUM_ReturnYards',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
