# Generated by Django 2.2.5 on 2019-12-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0037_playergamestat_gamesplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='PlayerFaceJson',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
