# Generated by Django 2.2.5 on 2019-12-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0040_auto_20191228_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerseasonskill',
            old_name='FinesseMoves_Rating',
            new_name='PassRush_Rating',
        ),
        migrations.RenameField(
            model_name='playerseasonskill',
            old_name='DeepRouteRunning_Rating',
            new_name='RouteRunning_Rating',
        ),
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='MediumRouteRunning_Rating',
        ),
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='PowerMoves_Rating',
        ),
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='ShortRouteRunning_Rating',
        ),
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='SpectacularCatch_Rating',
        ),
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='SpinMove_Rating',
        ),
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='StiffArm_Rating',
        ),
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='Toughness_Rating',
        ),
        migrations.RemoveField(
            model_name='playerseasonskill',
            name='Trucking_Rating',
        ),
    ]
