# Generated by Django 2.2.5 on 2019-12-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0041_auto_20191228_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='TwoPointAttempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='TwoPointConversion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='TwoPointAttempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='TwoPointConversion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
