# Generated by Django 2.2.5 on 2019-12-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0042_auto_20191228_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGA29',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGA39',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGA49',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGA50',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGM29',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGM39',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGM49',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_FGM50',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='KCK_FGA29',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='KCK_FGA39',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='KCK_FGA49',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='KCK_FGA50',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='KCK_FGM29',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='KCK_FGM39',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='KCK_FGM49',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='KCK_FGM50',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KCK_FGA29',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KCK_FGA39',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KCK_FGA49',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KCK_FGA50',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KCK_FGM29',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KCK_FGM39',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KCK_FGM49',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KCK_FGM50',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='KCK_FGA29',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='KCK_FGA39',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='KCK_FGA49',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='KCK_FGA50',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='KCK_FGM29',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='KCK_FGM39',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='KCK_FGM49',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='KCK_FGM50',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
