# Generated by Django 2.2.5 on 2019-12-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0043_auto_20191228_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_playerarchetyperatingmodifier',
            old_name='DeepRouteRunning_Rating',
            new_name='RouteRunning_Rating',
        ),
        migrations.RemoveField(
            model_name='system_playerarchetyperatingmodifier',
            name='MediumRouteRunning_Rating',
        ),
        migrations.RemoveField(
            model_name='system_playerarchetyperatingmodifier',
            name='ShortRouteRunning_Rating',
        ),
    ]
