# Generated by Django 2.2.5 on 2019-12-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0045_playerteamseasondepthchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassAbbreviation', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('ClassName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('IsRecruit', models.BooleanField(default=False)),
            ],
        ),
    ]
