# Generated by Django 2.2.5 on 2019-12-30 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0046_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Class',
        ),
        migrations.AddField(
            model_name='class',
            name='ClassSortOrder',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ClassID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Class'),
        ),
    ]
