# Generated by Django 2.2.5 on 2019-12-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0047_auto_20191230_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerteamseason',
            name='PlayerClass',
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='PlayerClassID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Class'),
        ),
    ]
