# Generated by Django 2.2.5 on 2019-12-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0048_auto_20191230_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerteamseason',
            old_name='PlayerClassID',
            new_name='ClassID',
        ),
    ]
