# Generated by Django 2.2.5 on 2019-12-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0049_auto_20191230_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerteamseasondepthchart',
            old_name='DepthPostion',
            new_name='DepthPosition',
        ),
    ]
