# Generated by Django 2.2.5 on 2019-12-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0051_auto_20191231_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='TeamGamesPlayed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='TeamGamesPlayed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
