# Generated by Django 2.2.5 on 2020-01-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0054_auto_20200101_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='OpposingTeamSeasonID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OpposingTeamSeasonID', to='HeadFootballCoach.TeamSeason'),
        ),
    ]
