# Generated by Django 2.2.5 on 2020-01-01 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0055_teamgame_opposingteamseasonid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgame',
            name='OpposingTeamSeasonID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opposingteamgame', to='HeadFootballCoach.TeamSeason'),
        ),
    ]
