# Generated by Django 2.2.5 on 2020-01-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0056_auto_20200101_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='Possessions',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
