# Generated by Django 2.2.5 on 2020-01-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0057_teamgame_possessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameevent',
            old_name='ScoringTeamID',
            new_name='DisplayTeamID',
        ),
    ]
