# Generated by Django 2.2.5 on 2020-01-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0058_auto_20200104_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayChoiceLog',
            fields=[
                ('PlayChoiceLogID', models.AutoField(primary_key=True, serialize=False)),
                ('BallSpot', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('YardsToGo', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('Down', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('OffensivePointDifferential', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('Period', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('SecondsLeftInPeriod', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('Run_Prob', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('Pass_Prob', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('Punt_Prob', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('FG_Prob', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('PlayClockUrgency', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
