# Generated by Django 2.2.5 on 2020-01-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0059_playchoicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='BLK_Blocks',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
