# Generated by Django 2.2.5 on 2020-01-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0060_playergamestat_blk_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='playchoicelog',
            name='GameID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Game'),
        ),
    ]
