# Generated by Django 2.2.5 on 2020-01-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0061_playchoicelog_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='TeamConferenceRecord',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='ExpectedWins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
