# Generated by Django 2.2.5 on 2020-01-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0062_auto_20200105_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playchoicelog',
            name='BallSpot',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playchoicelog',
            name='Down',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playchoicelog',
            name='FG_Prob',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playchoicelog',
            name='Pass_Prob',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playchoicelog',
            name='Period',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playchoicelog',
            name='PlayClockUrgency',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playchoicelog',
            name='Punt_Prob',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playchoicelog',
            name='Run_Prob',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playchoicelog',
            name='SecondsLeftInPeriod',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playchoicelog',
            name='YardsToGo',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
