# Generated by Django 2.2.5 on 2020-01-05 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0063_auto_20200105_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPositionGroup',
            fields=[
                ('CoachPositionGroupID', models.AutoField(primary_key=True, serialize=False)),
                ('CoachPositionGroupName', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoachPosition',
            fields=[
                ('CoachPositionID', models.AutoField(primary_key=True, serialize=False)),
                ('CoachPositionAbbreviation', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('CoachPositionName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('CoachPositionMinimumCountPerTeam', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('CoachPositionSortOrder', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('CoachPositionGroupID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.CoachPositionGroup')),
                ('CoachPositionParentID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.CoachPosition')),
            ],
        ),
    ]
