# Generated by Django 2.2.5 on 2020-01-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0064_coachposition_coachpositiongroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachposition',
            old_name='CoachPositionMinimumCountPerTeam',
            new_name='CoachPositionCountPerTeam',
        ),
    ]
