# Generated by Django 2.2.5 on 2020-01-05 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0065_auto_20200105_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachposition',
            name='CoachPositionGroupID',
        ),
        migrations.AddField(
            model_name='coachposition',
            name='PositionGroupID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.PositionGroup'),
        ),
        migrations.AddField(
            model_name='coachposition',
            name='PositionID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Position'),
        ),
    ]
