# Generated by Django 2.2.5 on 2020-01-05 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0066_auto_20200105_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachPositionGroup',
        ),
        migrations.RemoveField(
            model_name='coachposition',
            name='PositionGroupID',
        ),
        migrations.RemoveField(
            model_name='coachposition',
            name='PositionID',
        ),
        migrations.AddField(
            model_name='position',
            name='CoachPositionID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.CoachPosition'),
        ),
    ]
