# Generated by Django 2.2.5 on 2020-01-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0068_auto_20200105_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachteamseason',
            name='Position',
        ),
        migrations.AddField(
            model_name='coachteamseason',
            name='CoachPositionID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.CoachPosition'),
        ),
    ]
