# Generated by Django 2.2.5 on 2020-01-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0070_auto_20200107_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachteamseason',
            name='FiredAfterSeason',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachteamseason',
            name='LeftForNewJobAfterSeason',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachteamseason',
            name='RetiredAfterSeason',
            field=models.BooleanField(default=False),
        ),
    ]
