# Generated by Django 3.0.2 on 2020-01-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0071_auto_20200109_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrivalry',
            name='PreferredWeekNumber',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
