# Generated by Django 3.0.2 on 2020-01-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0072_teamrivalry_preferredweeknumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='HeadlineTextHTML',
            new_name='HeadlineHref',
        ),
        migrations.RenameField(
            model_name='headline',
            old_name='DateID',
            new_name='WeekID',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='HeadlineType',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='Player1PlayerTeamSeasonID',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='Player2PlayerTeamSeasonID',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='Team1TeamID',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='Team2TeamID',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='Team3TeamID',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='Team4TeamID',
        ),
    ]
