# Generated by Django 3.0.2 on 2020-01-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0074_auto_20200118_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveplay',
            name='ClockIsRunning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsChangeOfPossessionPlay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsDefensiveTouchdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsFieldGoalAttempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsFieldGoalMake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsFirstDown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsFumble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsFumbleRecoveryDefense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsInterception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsKneel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsPunt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsRun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='IsScoringPlay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='PlayDescription',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driveplay',
            name='PlayYards',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='AwayPoints',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='DefensiveTeamGameID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defensivegamedrive', to='HeadFootballCoach.TeamGame'),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='DriveDescription',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='DriveDuration',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='DrivePlayCount',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='DriveStartBallSpot',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='DriveYards',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='EventPeriod',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='EventTime',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='HomePoints',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='OffensiveTeamGameID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offensivegamedrive', to='HeadFootballCoach.TeamGame'),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='ScoreOnDrive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamedrive',
            name='TurnoverOnDrive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driveplay',
            name='GameDriveID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.GameDrive'),
        ),
    ]
