# Generated by Django 3.0.2 on 2020-01-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0075_auto_20200118_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driveplay',
            old_name='PlayChoiceLogID',
            new_name='DrivePlayID',
        ),
        migrations.RemoveField(
            model_name='driveplay',
            name='PlayChoice',
        ),
        migrations.AddField(
            model_name='driveplay',
            name='PlayDuration',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
