# Generated by Django 3.0.2 on 2020-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0076_auto_20200119_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedrive',
            name='AwayPoints',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamedrive',
            name='DriveDescription',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gamedrive',
            name='EventPeriod',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamedrive',
            name='EventTime',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamedrive',
            name='HomePoints',
            field=models.SmallIntegerField(default=0),
        ),
    ]
