# Generated by Django 3.0.2 on 2020-01-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0077_auto_20200119_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='ShowNextWeek',
            field=models.BooleanField(default=False),
        ),
    ]
