# Generated by Django 3.0.2 on 2020-02-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0078_headline_shownextweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamseason',
            name='GraduatedAfterSeason',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='LeftEarlyForDraftAfterSeason',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='QuitFootballAfterSeason',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='TransferredAfterSeason',
            field=models.BooleanField(default=False),
        ),
    ]
