# Generated by Django 3.0.2 on 2020-02-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0079_auto_20200209_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamseason',
            name='LeavingTeamAfterSeason',
            field=models.BooleanField(default=True),
        ),
    ]
