# Generated by Django 3.0.2 on 2020-02-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0080_playerteamseason_leavingteamafterseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='OvertimeLength_Minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='league',
            name='PeriodLength_Minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='league',
            name='PlayClockLength',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='team',
            name='StadiumCapacity',
            field=models.IntegerField(default=30000),
        ),
    ]
