# Generated by Django 3.0.2 on 2020-03-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0081_auto_20200210_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='RecruitingStage',
            field=models.CharField(default='Not Recruiting', max_length=40),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='IsActivelyRecruiting',
            field=models.BooleanField(default=True),
        ),
    ]
