# Generated by Django 3.0.2 on 2020-03-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0082_auto_20200305_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitteamseason',
            name='DistanceMatchRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Preference1MatchRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Preference1Name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Preference2MatchRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Preference2Name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Preference3MatchRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Preference3Name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='recruitteamseason',
            name='IsActivelyRecruiting',
            field=models.BooleanField(default=False),
        ),
    ]
