# Generated by Django 3.0.2 on 2020-03-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0084_recruitteamseason_teamprestigerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='NumberTeam',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='audit',
            name='ScalesWithTeams',
            field=models.BooleanField(default=False),
        ),
    ]
