# Generated by Django 3.0.2 on 2020-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0085_auto_20200307_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='RecruitingPointsNeeded',
            field=models.PositiveSmallIntegerField(default=2500),
        ),
    ]
