# Generated by Django 3.0.2 on 2020-03-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0086_player_recruitingpointsneeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitteamseason',
            name='RecruitingTeamRank',
            field=models.IntegerField(default=1),
        ),
    ]
