# Generated by Django 3.0.2 on 2020-04-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0087_recruitteamseason_recruitingteamrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='TopStatStringDisplay1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='TopStatStringDisplay2',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
