# Generated by Django 3.0.2 on 2020-04-06 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0088_auto_20200405_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Recruiting_40Time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='player',
            name='Recruiting_BenchPressReps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Recruiting_VerticalJump',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='TeamSeasonPosition',
            fields=[
                ('TeamSeasonPositionID', models.AutoField(primary_key=True, serialize=False)),
                ('PositionPriority', models.IntegerField(default=0)),
                ('PositionPreference', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('CurrentPlayerCount', models.IntegerField(default=0)),
                ('MinimumPlayerCount', models.IntegerField(default=0)),
                ('NeededPlayerCount', models.IntegerField(default=0)),
                ('CommitPlayerCount', models.IntegerField(default=0)),
                ('FreshmanPlayerCount', models.IntegerField(default=0)),
                ('SophomorePlayerCount', models.IntegerField(default=0)),
                ('JuniorPlayerCount', models.IntegerField(default=0)),
                ('SeniorPlayerCount', models.IntegerField(default=0)),
                ('Year1PositionOverall', models.IntegerField(default=0)),
                ('Year2PositionOverall', models.IntegerField(default=0)),
                ('Year3PositionOverall', models.IntegerField(default=0)),
                ('PositionID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Position')),
                ('TeamSeasonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamSeason')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
