# Generated by Django 3.0.2 on 2020-04-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0091_auto_20200407_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='DefaultDefensiveScheme',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='DefaultOffensiveScheme',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
