# Generated by Django 3.0.2 on 2020-04-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0092_auto_20200407_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='TeamJerseyInvert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
