# Generated by Django 3.0.2 on 2020-04-08 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0093_auto_20200408_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgame',
            name='OpposingTeamGameID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamgame_opposingteamgame', to='HeadFootballCoach.TeamGame'),
        ),
    ]
