# Generated by Django 3.0.2 on 2020-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0094_auto_20200408_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='PositionTypicalStarterCountPerTeam',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='TeamJerseyInvert',
            field=models.BooleanField(default=False),
        ),
    ]
