# Generated by Django 3.0.2 on 2020-04-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0095_auto_20200408_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='PositionMaximumCountPerTeam',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
