# Generated by Django 3.0.2 on 2020-04-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0096_position_positionmaximumcountperteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPosition',
            fields=[
                ('SubPositionID', models.AutoField(primary_key=True, serialize=False)),
                ('SubPositionAbbreviation', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('SubPositionName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('SubPositionSortOrder', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PositionID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Position')),
            ],
        ),
    ]
