# Generated by Django 3.0.2 on 2020-04-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0097_subposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='subposition',
            name='PositionTypicalStarterCountPerTeam',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
