# Generated by Django 3.0.2 on 2020-04-15 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0101_auto_20200414_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='StadiumCapacity',
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('StadiumID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('StadiumName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('StadiumImageURL', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('StadiumCapacity', models.IntegerField(default=0)),
                ('CityID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.City')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='StadiumID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Stadium'),
        ),
    ]
