# Generated by Django 3.0.2 on 2020-04-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0102_auto_20200415_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='TeamDefenseRating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='TeamOffenseRating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
