# Generated by Django 3.0.2 on 2020-04-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0103_auto_20200418_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='TeamDefenseRating_Grade',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='TeamOffenseRating_Grade',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='TeamOverallRating_Grade',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
