# Generated by Django 3.0.2 on 2020-04-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0104_auto_20200418_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='HoldConferenceChampionshipGame',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='IsIndependent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conference',
            name='NumberConferenceGames',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
