# Generated by Django 3.0.2 on 2020-04-19 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0105_auto_20200418_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='BlitzStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='CB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='CoveragePressStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='CoverageStyleStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='DE_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='DL_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='MLB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='OLB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='OL_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='PassingStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='QB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='RB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='RunningBackStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='S_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='TE_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='WR_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='TeamSeasonStrategy',
            fields=[
                ('TeamSeasonStrategyID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('TeamSeasonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamSeason')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
