# Generated by Django 3.0.2 on 2020-04-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0106_auto_20200419_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='DL_Preference',
            new_name='DT_Preference',
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='BlitzStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='CB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='CoveragePressStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='CoverageStyleStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='DE_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='DT_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='DefensivePlaybook',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='MLB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='OLB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='OL_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='OffensivePlaybook',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='PassingStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='PlayClockAggressivenessTendency',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='PlaycallPassTendency',
            field=models.PositiveSmallIntegerField(default=55),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='QB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='RB_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='RunningBackStrategy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='S_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='SituationalAggressivenessTendency',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='TE_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstrategy',
            name='WR_Preference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
