# Generated by Django 3.0.2 on 2020-04-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0108_auto_20200420_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='KCK_LNG',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KCK_LNG',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='KR_LNG',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
