# Generated by Django 3.0.2 on 2020-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0109_auto_20200420_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='FirstDowns_Pass',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='FirstDowns_Rush',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
