# Generated by Django 3.0.2 on 2020-04-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0110_auto_20200422_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonposition',
            name='StarterPlayerCount',
            field=models.IntegerField(default=0),
        ),
    ]
