# Generated by Django 3.0.2 on 2020-04-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0111_teamseasonposition_starterplayercount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_playerarchetyperatingmodifier',
            name='Injury_Rating',
        ),
        migrations.RemoveField(
            model_name='system_playerarchetyperatingmodifier',
            name='SpectacularCatch_Rating',
        ),
        migrations.RemoveField(
            model_name='system_playerarchetyperatingmodifier',
            name='SpinMove_Rating',
        ),
        migrations.RemoveField(
            model_name='system_playerarchetyperatingmodifier',
            name='StiffArm_Rating',
        ),
        migrations.RemoveField(
            model_name='system_playerarchetyperatingmodifier',
            name='Toughness_Rating',
        ),
    ]
