# Generated by Django 3.0.2 on 2020-04-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0112_auto_20200424_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_playerarchetyperatingmodifier',
            name='Trucking_Rating',
        ),
    ]
