# Generated by Django 3.0.2 on 2020-04-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0113_remove_system_playerarchetyperatingmodifier_trucking_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_playerarchetyperatingmodifier',
            old_name='FinesseMoves_Rating',
            new_name='PassRush_Rating',
        ),
        migrations.RemoveField(
            model_name='system_playerarchetyperatingmodifier',
            name='PowerMoves_Rating',
        ),
    ]
