# Generated by Django 3.0.2 on 2020-04-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0115_auto_20200424_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='TeamLogoURL_100',
            field=models.CharField(blank=True, default=None, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='TeamLogoURL_50',
            field=models.CharField(blank=True, default=None, max_length=99, null=True),
        ),
    ]
