# Generated by Django 3.0.2 on 2020-05-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0116_auto_20200429_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='IsCurrentlyRedshirted',
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='RedshirtedThisSeason',
            field=models.BooleanField(default=False),
        ),
    ]
