# Generated by Django 3.0.2 on 2020-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0117_auto_20200503_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='RedshirtTendency',
            field=models.SmallIntegerField(default=0),
        ),
    ]
