# Generated by Django 3.0.2 on 2020-05-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0118_coach_redshirttendency'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='PlayersPerTeam',
            field=models.PositiveSmallIntegerField(default=64),
        ),
    ]
