# Generated by Django 3.0.2 on 2020-05-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0119_league_playersperteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='PatienceTendency',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coach',
            name='VeteranTendency',
            field=models.SmallIntegerField(default=0),
        ),
    ]
