# Generated by Django 3.0.2 on 2020-05-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0120_auto_20200505_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitteamseason',
            name='ScoutingFuzz',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
