# Generated by Django 3.0.2 on 2020-05-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0121_recruitteamseason_scoutingfuzz'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamseason',
            name='TeamCaptain',
            field=models.BooleanField(default=False),
        ),
    ]
