# Generated by Django 3.0.2 on 2020-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0122_playerteamseason_teamcaptain'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='IsUpperClassman',
            field=models.BooleanField(default=False),
        ),
    ]
