# Generated by Django 3.0.2 on 2020-05-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0123_class_isupperclassman'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueseason',
            name='Preseason_UserCutPlayers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leagueseason',
            name='Preseason_UserSetCaptains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leagueseason',
            name='Preseason_UserSetDepthChart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leagueseason',
            name='Preseason_UserSetGameplan',
            field=models.BooleanField(default=False),
        ),
    ]
