# Generated by Django 3.0.2 on 2020-05-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0124_auto_20200509_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ClassID',
        ),
    ]
