# Generated by Django 3.0.2 on 2020-05-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0125_remove_player_classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerteamseason',
            name='LeavingTeamAfterSeason',
            field=models.BooleanField(default=False),
        ),
    ]
