# Generated by Django 3.0.2 on 2020-05-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0127_auto_20200513_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='IsFreeAgentTeam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='IsRecruitTeam',
            field=models.BooleanField(default=False),
        ),
    ]
