# Generated by Django 3.0.2 on 2020-05-13 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0128_auto_20200513_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTeamSeasonSkill',
            fields=[
                ('PlayerSeasonSkillID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Strength_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Agility_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Speed_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Acceleration_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Stamina_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Awareness_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Jumping_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Injury_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ThrowPower_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ShortThrowAccuracy_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('MediumThrowAccuracy_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('DeepThrowAccuracy_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ThrowOnRun_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ThrowUnderPressure_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PlayAction_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Elusiveness_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('BallCarrierVision_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('JukeMove_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('BreakTackle_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Carrying_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Catching_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('CatchInTraffic_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('RouteRunning_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Release_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('HitPower_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Tackle_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PassRush_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('BlockShedding_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Pursuit_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PlayRecognition_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ManCoverage_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ZoneCoverage_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Press_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PassBlock_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('RunBlock_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('ImpactBlock_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('KickPower_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('KickAccuracy_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('KickReturn_Rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('OverallRating', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('PlayerTeamSeasonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.PlayerTeamSeason')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerSeasonSkill',
        ),
    ]
