# Generated by Django 3.0.2 on 2020-05-13 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0129_auto_20200513_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseason',
            name='LeagueSeasonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.LeagueSeason'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='TeamID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Team'),
        ),
    ]
