# Generated by Django 3.0.2 on 2020-05-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0130_auto_20200513_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerteamseasonskill',
            old_name='PlayerSeasonSkillID',
            new_name='PlayerTeamSeasonSkillID',
        ),
    ]
