# Generated by Django 3.0.2 on 2020-05-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0131_auto_20200513_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='ConferenceID',
            new_name='OriginalConferenceID',
        ),
        migrations.AddField(
            model_name='teamseason',
            name='ConferenceID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Conference'),
        ),
    ]
