# Generated by Django 3.0.2 on 2020-05-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0132_auto_20200513_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='AcademicPrestigeRating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='CampusLifestyleRating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ChampionshipContenderRating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='CoachStabilityRating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='FacilitiesRating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='LocationRating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='OriginalConferenceID',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ProPotentialRating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='TeamPrestige',
        ),
        migrations.RemoveField(
            model_name='team',
            name='TelevisionExposureRating',
        ),
        migrations.AddField(
            model_name='teamseason',
            name='AcademicPrestigeRating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='CampusLifestyleRating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='ChampionshipContenderRating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='CoachStabilityRating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='FacilitiesRating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='LocationRating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='ProPotentialRating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='TeamPrestige',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='TelevisionExposureRating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TeamConference',
        ),
    ]
