# Generated by Django 3.0.2 on 2020-05-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0133_auto_20200514_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='PlayerID',
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='PlayerTeamSeasonID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.PlayerTeamSeason'),
            preserve_default=False,
        ),
    ]
