# Generated by Django 3.0.2 on 2020-05-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0135_week_recruitingweekmodifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='WeekNumber',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
