# Generated by Django 3.0.2 on 2020-05-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0136_auto_20200516_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='RecruitingAllowed',
            field=models.BooleanField(default=False),
        ),
    ]
