# Generated by Django 3.0.2 on 2020-05-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0137_week_recruitingallowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='FirstWeekOfCalendar',
            field=models.BooleanField(default=False),
        ),
    ]
