# Generated by Django 3.0.2 on 2020-05-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0138_week_firstweekofcalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerteamseasonskill',
            name='PlayerTeamSeasonID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.PlayerTeamSeason'),
        ),
    ]
