# Generated by Django 3.0.2 on 2020-05-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0139_auto_20200517_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='DevelopmentRating',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
