# Generated by Django 3.0.2 on 2020-05-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0140_auto_20200517_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitteamseason',
            old_name='ScoutedOverall',
            new_name='Scouted_Overall',
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Acceleration_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Agility_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Awareness_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_BallCarrierVision_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_BlockShedding_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_BreakTackle_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Carrying_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_CatchInTraffic_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Catching_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_DeepThrowAccuracy_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Elusiveness_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_HitPower_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_ImpactBlock_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Injury_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_JukeMove_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Jumping_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_KickAccuracy_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_KickPower_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_KickReturn_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_ManCoverage_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_MediumThrowAccuracy_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_PassBlock_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_PassRush_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_PlayAction_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_PlayRecognition_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Press_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Pursuit_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Release_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_RouteRunning_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_RunBlock_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_ShortThrowAccuracy_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Speed_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Stamina_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Strength_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_Tackle_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_ThrowOnRun_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_ThrowPower_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_ThrowUnderPressure_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='Scouted_ZoneCoverage_Rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
