# Generated by Django 3.0.2 on 2020-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0141_auto_20200517_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='QueryCount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
