# Generated by Django 3.0.2 on 2020-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0142_audit_querycount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='QueryCount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
