# Generated by Django 3.0.2 on 2020-05-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0144_auto_20200518_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_playerarchetyperatingmodifier',
            name='PositionID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Position'),
        ),
    ]
