# Generated by Django 3.0.2 on 2020-05-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0146_auto_20200519_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='MaxSignablePlayersPerTeam',
            field=models.PositiveSmallIntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='league',
            name='PlayersPerTeam',
            field=models.PositiveSmallIntegerField(default=75),
        ),
    ]
