# Generated by Django 3.0.2 on 2020-05-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0148_auto_20200522_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRecruitingInterest',
            fields=[
                ('PlayerRecruitingInterestID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('InterestName', models.CharField(max_length=50)),
                ('InterestRank', models.IntegerField(default=0)),
                ('PlayerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Player')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
