# Generated by Django 3.0.2 on 2020-05-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0149_playerrecruitinginterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='AcademicPrestigeValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='CampusLifestyleValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ChampionshipContenderValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='CloseToHomeValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='CoachStabilityValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='CoachStyleValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='FacilitiesValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='PlayingTimeValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ProPotentialValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='TeamPrestigeValue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='TelevisionExposureValue',
        ),
    ]
