# Generated by Django 3.0.2 on 2020-05-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0150_auto_20200523_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitteamseason',
            name='CommitWeekID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitweek_recruitteamseason', to='HeadFootballCoach.Week'),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='VisitWeekID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitweek_recruitteamseason', to='HeadFootballCoach.Week'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='game',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='league',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='leagueseason',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='player',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='playergamestat',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='playerrecruitinginterest',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='playerteamseason',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='playerteamseasondepthchart',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='playerteamseasonskill',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='recruitteamseason',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='team',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='teamgame',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='teamrivalry',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='teamseasonstrategy',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
        migrations.AlterField(
            model_name='week',
            name='WorldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World'),
        ),
    ]
