# Generated by Django 3.0.2 on 2020-05-23 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0151_auto_20200523_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitTeamSeasonInterest',
            fields=[
                ('RecruitTeamSeasonInterestID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('DefaultInclude', models.BooleanField(default=False)),
                ('PitchName', models.CharField(max_length=50)),
                ('PitchRecruitInterestRank', models.IntegerField(blank=True, default=None, null=True)),
                ('TeamRating', models.IntegerField(default=0)),
                ('PlayerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Player')),
                ('WorldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
        migrations.RenameField(
            model_name='playerrecruitinginterest',
            old_name='InterestName',
            new_name='PitchName',
        ),
        migrations.RenameField(
            model_name='playerrecruitinginterest',
            old_name='InterestRank',
            new_name='PitchRecruitInterestRank',
        ),
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='DistanceMatchRating',
        ),
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='MatchRating',
        ),
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='Preference1MatchRating',
        ),
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='Preference1Name',
        ),
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='Preference2MatchRating',
        ),
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='Preference2Name',
        ),
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='Preference3MatchRating',
        ),
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='Preference3Name',
        ),
        migrations.RemoveField(
            model_name='recruitteamseason',
            name='TeamPrestigeRating',
        ),
        migrations.RemoveField(
            model_name='state',
            name='NationID',
        ),
        migrations.AddField(
            model_name='state',
            name='RegionID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Region'),
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
    ]
