# Generated by Django 3.0.2 on 2020-05-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0155_teamseasoninforating_teamrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfotopic',
            name='RecruitInterestWeight',
            field=models.IntegerField(default=1),
        ),
    ]
