# Generated by Django 3.0.2 on 2020-05-24 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0156_teaminfotopic_recruitinterestweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitteamseasoninterest',
            name='PitchRecruitInterestRank',
        ),
        migrations.RemoveField(
            model_name='recruitteamseasoninterest',
            name='PlayerID',
        ),
        migrations.RemoveField(
            model_name='recruitteamseasoninterest',
            name='TeamInfoTopicID',
        ),
        migrations.RemoveField(
            model_name='recruitteamseasoninterest',
            name='TeamRating',
        ),
        migrations.AddField(
            model_name='recruitteamseasoninterest',
            name='PitchRecruitInterestRank_IsKnown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitteamseasoninterest',
            name='PlayerRecruitingInterestID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.PlayerRecruitingInterest'),
        ),
        migrations.AddField(
            model_name='recruitteamseasoninterest',
            name='RecruitTeamSeasonID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.RecruitTeamSeason'),
        ),
        migrations.AddField(
            model_name='recruitteamseasoninterest',
            name='TeamSeasonInfoRatingID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamSeasonInfoRating'),
        ),
    ]
