# Generated by Django 3.0.2 on 2020-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0157_auto_20200524_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitteamseasoninterest',
            name='TeamSeasonInfoRatingID',
        ),
        migrations.AddField(
            model_name='recruitteamseasoninterest',
            name='TeamRating',
            field=models.IntegerField(default=0),
        ),
    ]
