# Generated by Django 3.0.2 on 2020-05-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0158_auto_20200524_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasoninforating',
            name='IsPrestigeOrLocation',
            field=models.BooleanField(default=False),
        ),
    ]
