# Generated by Django 3.0.2 on 2020-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0159_teamseasoninforating_isprestigeorlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamseasoninforating',
            name='IsPrestigeOrLocation',
        ),
        migrations.AddField(
            model_name='teaminfotopic',
            name='IsPrestigeOrLocation',
            field=models.BooleanField(default=False),
        ),
    ]
