# Generated by Django 3.0.2 on 2020-05-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0160_auto_20200530_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='RecruitingConcentration',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitteamseason',
            name='UserRecruitingPointsThisWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='week',
            name='UserRecruitingPointsLeft',
            field=models.IntegerField(default=0),
        ),
    ]
