# Generated by Django 3.0.2 on 2020-05-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0161_auto_20200530_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='RecruitingOverallAdjustment',
            field=models.SmallIntegerField(default=0),
        ),
    ]
