# Generated by Django 3.0.2 on 2020-05-31 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0162_position_recruitingoveralladjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSeason',
            fields=[
                ('ConferenceSeasonID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('ConferenceID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Conference')),
                ('LeagueSeasonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.LeagueSeason')),
                ('WorldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='ConferenceID',
        ),
        migrations.CreateModel(
            name='DivisionSeason',
            fields=[
                ('DivisionSeasonID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('DivisionName', models.CharField(max_length=100)),
                ('ConferenceSeasonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.ConferenceSeason')),
                ('LeagueSeasonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.LeagueSeason')),
                ('WorldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
        migrations.AddField(
            model_name='teamseason',
            name='DivisionSeasonID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.DivisionSeason'),
        ),
    ]
