# Generated by Django 3.0.2 on 2020-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0163_auto_20200531_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionseason',
            name='SoleDivision',
            field=models.BooleanField(default=True),
        ),
    ]
