# Generated by Django 3.0.2 on 2020-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0164_divisionseason_soledivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionseason',
            name='DivisionName',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
