# Generated by Django 3.0.2 on 2020-06-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0166_auto_20200531_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamseason',
            name='TopStatStringDisplay1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='TopStatStringDisplay2',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
