# Generated by Django 3.0.2 on 2020-06-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0167_auto_20200604_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='TopStatStringDisplay3',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='TopStatStringDisplay4',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='TopStatStringDisplay3',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='TopStatStringDisplay4',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
