# Generated by Django 3.0.2 on 2020-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0168_auto_20200605_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='RecruitingPointsNeeded',
            field=models.SmallIntegerField(default=2500),
        ),
    ]
