# Generated by Django 3.0.2 on 2020-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0169_auto_20200611_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='RecruitingPointsNeeded',
            field=models.IntegerField(default=2500),
        ),
    ]
