# Generated by Django 3.0.7 on 2020-07-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0170_auto_20200611_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='MaxRecruitingPointsPerPlayerPerWeek',
            field=models.IntegerField(default=6),
        ),
    ]
