# Generated by Django 3.0.7 on 2020-07-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0171_teamseason_maxrecruitingpointsperplayerperweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitteamseasoninterest',
            name='UtilizedThisWeek',
            field=models.BooleanField(default=False),
        ),
    ]
