# Generated by Django 3.0.7 on 2020-07-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0172_recruitteamseasoninterest_utilizedthisweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitteamseason',
            old_name='UserRecruitingPointsThisWeek',
            new_name='UserRecruitingPointsLeftThisWeek',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='UserRecruitingPointsLeft',
            new_name='UserRecruitingPointsLeftThisWeek',
        ),
    ]
