# Generated by Django 3.0.7 on 2020-07-07 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0173_auto_20200704_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitingPromise',
            fields=[
                ('RecruitingPromiseID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('PromiseText', models.CharField(default='Promise', max_length=50)),
                ('TextDescription', models.CharField(default='Promise', max_length=250)),
                ('PitchValue', models.IntegerField(default=0)),
                ('AllowInclusiveOption', models.BooleanField(default=True)),
                ('ExtraYearExclusiveMultiplier', models.FloatField(default=1.0)),
                ('ExtraYearInclusiveMultiplier', models.FloatField(default=1.0)),
                ('TeamInfoTopicID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamInfoTopic')),
            ],
        ),
    ]
