# Generated by Django 3.0.7 on 2020-07-07 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0174_recruitingpromise'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitTeamSeasonPromise',
            fields=[
                ('RecruitTeamSeasonPromiseID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('PromiseMade', models.BooleanField(default=False)),
                ('PromiseKept', models.BooleanField(default=False)),
                ('RecruitTeamSeasonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.RecruitTeamSeason')),
                ('RecruitingPromiseID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.RecruitingPromise')),
                ('WorldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
