# Generated by Django 3.0.7 on 2020-07-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0176_auto_20200707_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonState',
            fields=[
                ('TeamSeasonStateID', models.AutoField(primary_key=True, serialize=False)),
                ('CurrentPlayerCount', models.IntegerField(default=0)),
                ('CommitPlayerCount', models.IntegerField(default=0)),
                ('FreshmanPlayerCount', models.IntegerField(default=0)),
                ('SophomorePlayerCount', models.IntegerField(default=0)),
                ('JuniorPlayerCount', models.IntegerField(default=0)),
                ('SeniorPlayerCount', models.IntegerField(default=0)),
                ('IsPipelineState', models.BooleanField(default=False)),
                ('IsConnectedState', models.BooleanField(default=False)),
                ('StateID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.State')),
                ('TeamSeasonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamSeason')),
                ('WorldID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
