# Generated by Django 3.0.7 on 2020-07-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0177_teamseasonstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstate',
            name='GamesInState',
            field=models.IntegerField(default=0),
        ),
    ]
