# Generated by Django 3.0.7 on 2020-07-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0178_teamseasonstate_gamesinstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='SVGPath',
            field=models.CharField(default='', max_length=2600),
        ),
    ]
