# Generated by Django 3.0.7 on 2020-07-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0179_state_svgpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitteamseason',
            name='TeamSeasonStateID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.TeamSeasonState'),
        ),
    ]
