# Generated by Django 3.0.7 on 2020-08-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0181_auto_20200809_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='ScoutSpeedRating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
