# Generated by Django 3.0.7 on 2020-08-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0182_coach_scoutspeedrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitteamseason',
            name='SkillGroupsLeftToScout',
            field=models.IntegerField(default=0),
        ),
    ]
