# Generated by Django 3.0.7 on 2020-11-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0184_week_messagestoviewthisweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekMessage',
            fields=[
                ('WeekMessageID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('MessageImportanceValue', models.PositiveSmallIntegerField(default=0)),
                ('MessageText', models.CharField(default='', max_length=400)),
                ('LinkText', models.CharField(default='', max_length=400)),
                ('LinkHref', models.CharField(default='', max_length=400)),
                ('LeagueSeasonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.LeagueSeason')),
                ('WeekID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.Week')),
                ('WorldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadFootballCoach.World')),
            ],
        ),
    ]
