# Generated by Django 3.0.7 on 2020-11-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0187_auto_20201108_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='PlayerFaceSVG',
            field=models.CharField(blank=True, default=None, max_length=40000, null=True),
        ),
    ]
