# Generated by Django 3.0.7 on 2020-12-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadFootballCoach', '0188_player_playerfacesvg'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitteamseason',
            name='RecruitingTeamPriorityRank',
            field=models.IntegerField(default=1),
        ),
    ]
